### Test Hello World endpoint
GET http://localhost:3001/

###

### Get API info
GET http://localhost:3001/scraper

###

### Test scrape single event
# IMPORTANT: Replace with a REAL, PUBLIC Facebook event ID
# To find an event ID:
# 1. Go to a public Facebook event
# 2. Copy the ID from URL: facebook.com/events/[EVENT_ID]
# 3. Make sure the event is PUBLIC (visible without login)

GET http://localhost:3001/scraper/event/1987385505448084

###

### Test scrape event with full URL
GET http://localhost:3001/scraper/event/https://www.facebook.com/events/1987385505448084

###

### Test scrape event list - upcoming events
# IMPORTANT: Replace with a REAL Facebook page/group ID that has public events
# Example: A dance studio, event venue, or public group

GET http://localhost:3001/scraper/events?pageId=123456789&eventType=upcoming

###

### Test scrape event list - past events
GET http://localhost:3001/scraper/events?pageId=123456789&eventType=past

###

### Test scrape event list - all events
GET http://localhost:3001/scraper/events?pageId=123456789

###
